version: '3.8'

services:
  app:
    build: ./courses-api
    volumes: 
      - ./courses-api:/app
    ports:
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
