version: '3'

services:
  app:
    build: ./course-api
    volumes: 
      - ./course-api:/app
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: courses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
